# -*- coding: utf-8 -*-
"""DDP_Dedenrafiakbar_tugas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v8cqiBbhkmrSl98qrB1nRROYB1sjitKf
"""

print("nomor 1")
kendaraan=["motor","vario125","124.8","hitam","2"]
print(kendaraan)
kendaraan.append("18.000.000")
kendaraan.append("matic")
print(kendaraan)
kendaraan.insert(2,"honda")
print(kendaraan)

pilih = int(input ("mau hitung apa? 1 untuk persegi, 2 untuk lingkaran, 3 segitiga"))

match pilih:
 case 1:
  print(int(input ("berapa sisinya?")) ** 2)
 case 2:
  print(3.14 * int(input ("berapa jari jari nya?")) **2)
 case 3:
  print(1/2 * int(input("berapa alasnya? ")) * int(input("berapa tingginya?")))
 case _:
  print("salah angka")

a = int(input())
if a % 2 == 0:print("bilangn genap")
else: print("bilangan ganjil")